build:
  command: git submodule update --init --recursive && hugo
  publish: public
  environment:
    HUGO_VERSION: 0.139.1


context:
  production:
    environment:
      GO_VERSION: "1.23"

redirects:
  - from: /fundamentalised
    to: https://buttondown.com/tstowx/archive
    status: 301
    force: true
