[build]
  command = "hugo"
  publish = "public"

[build.environment]
  HUGO_VERSION = "0.139.1"

[[redirects]]
  from = "https://photos.tstowx.com/photos/*"
  to = "https://photos.tstowx.com/:splat"
  status = 301
  force = true
